name: fasttrack
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - pandas>=1.5
      - numpy
      - scikit-learn
      - matplotlib
      - requests
      - fpdf>=1.7.2
      - python-dateutil
      - pytz
      - joblib
      - streamlit
      - lxml
